// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIS9XCfs9exBGKQp_FDS3zk3CDuu3Wnsg',
    appId: '1:684619529594:web:061e4c0c5c6ed715f0aac3',
    messagingSenderId: '684619529594',
    projectId: 'nutricare-dc856',
    authDomain: 'nutricare-dc856.firebaseapp.com',
    storageBucket: 'nutricare-dc856.firebasestorage.app',
    measurementId: 'G-BBGQDG55ZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtvmb6dG74Y_8DnidxEyPiw42BiHm0E8M',
    appId: '1:684619529594:android:4de7312820256b7af0aac3',
    messagingSenderId: '684619529594',
    projectId: 'nutricare-dc856',
    storageBucket: 'nutricare-dc856.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJAaHwl7hnwwop2qU30tHIMXd2rJ1EpYA',
    appId: '1:684619529594:ios:b40e443387938985f0aac3',
    messagingSenderId: '684619529594',
    projectId: 'nutricare-dc856',
    storageBucket: 'nutricare-dc856.firebasestorage.app',
    iosBundleId: 'com.example.nutricare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJAaHwl7hnwwop2qU30tHIMXd2rJ1EpYA',
    appId: '1:684619529594:ios:b40e443387938985f0aac3',
    messagingSenderId: '684619529594',
    projectId: 'nutricare-dc856',
    storageBucket: 'nutricare-dc856.firebasestorage.app',
    iosBundleId: 'com.example.nutricare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIS9XCfs9exBGKQp_FDS3zk3CDuu3Wnsg',
    appId: '1:684619529594:web:76534b2868dd320bf0aac3',
    messagingSenderId: '684619529594',
    projectId: 'nutricare-dc856',
    authDomain: 'nutricare-dc856.firebaseapp.com',
    storageBucket: 'nutricare-dc856.firebasestorage.app',
    measurementId: 'G-T0GRMLFB8F',
  );

}